MASSAGE TEXT MT199
USER:INTMBLUSER
DOCUMENT HISTORY:20220615110043
MESSAGE DATE:15.06.2022 01:03:49
MESSAGE TYPE /TOUR/I MT199
MESSAGE REFERENCE:S005493022062901
/DEUTSCHE BANK AG
/TAUNUSANLAGE 12 60325 FRANKFURT AM MAIN.GERMANY 
/DEUTDEDBHAM/
/TO/
/PT BANK NEGARA INDONESIA/BNINIDJA/
/BANK BNI KCP MALL AMBASADORJALAN PROFESSOR DOKTOR SATRIO, RT.7/RW.4, KARET/
/BNINIDJA/
UETR: f316959c-950f-47a9-a94e-f266aae0457a
MT199 PROOF OF FUNDS
NOTIFICATION:
DELIVERY STATUS: DELIVERED
PRIORITY / DELIVERY: URGENT
MESSAGENUMBER::715691
-------------------------------------MESSAGE HEADER------------------------------------------
SWIFT INPUT: MT199 PROOF OF FUNDS
SENDER: FDS FUTURE DESIGN SYSTEMS GMBH
SWIFT CODE: DEUTDEDBHAM
BANK OFFICER: TBA
AMOUNT: €48,000,000.00
ACCOUNT NAME: FDS FUTURE DESIGN SYSTEMS GMBH
ACCOUNT NUMBER: DE25 2007 0024 0316 9000 00
RECEIVER: PT TUBANG KARYA MANDIRI COMPANY
BANK NAME BANK: PT BANK NEGARA INDONESIA
BANK ADDRESS: BANK BNI KCP MALL AMBASADORJALAN PROFESSOR DOKTOR SATRIO, RT.7/RW.4, KARET
KUNINGAN, RT.11/RW.4, KUNINGAN, KARET KUNINGAN, JAKARTA SELATAN, KOTA JAKARTA SELATAN DAERAH
KHUSUS IBUKOTA JAKARTA 12940
ACCOUNT NAME: PT TUBANG KARYA MANDIRI
IBAN NO: 1341492292
SWIFT CODE/BIC: BNINIDJA
BANK OFFICER: TB.MOCH.ARDY.HENDARSYAH@BNI.CO.ID
CURRENCY: EURO
AMOUNT: €48,000,000.00
----------------------------------------SWIFT MESSAGE TEXT-----------------------------------
TRANSACTION CODE: 335DB673F9756541
TRANSACTION NUMBER: 513494
UETR NUMBER: f316959c-950f-47a9-a94e-f266aae0457a
MESSAGE REFERENCE NUMBER: S005493022062901
WE HEREBY CONFIRM, WITH FULL BANK RESPONSIBILITY THAT WE DEUTSCHE BANK PRİVAT UND
GESCHÄFTSKUNDEN AG ON BEHALF OF OUR CLIENT: FDS FUTURE DESIGN SYSTEMS GMBH HAS AVAILABLE
FUNDS IN ACCOUNT NO. DE25 2007 0024 0316 9000 00 THE SUM OF EUROS 48,000,000.00 WHICH IS
FREELY TRANSFERABLE AND LEGALLY EARNED, GOOD, CLEAN AND CLEARED FUNDS OF NON-CRIMINAL ORIGIN,
FREE OF ANY LIENS OR ENCUMBRANCES AND ARE READY, WILLING AND ABLE TO CONFIRM THIS MT 199 ON
BANK-TO-BANK BASIS. WE THANK YOU FOR YOUR ATTENDANCE TO THIS QUERY PROMPTLY BY CREDITING THE
BENEFICIARY. PLEASE QUOTE OUR REF 210817DEUTDEDBMAG IN YOUR FUTURE CORRESPONDENCE RELATING TO
THIS CASE.
THE AUTHENTICITY AND VALIDITY OF THIS BANK CONFIRMATION LETTER CAN BE CONFIRMED BY
RESPONSIBLE BANK INQUIRY ON BANK-TO-BANK BASIS FOR AND ON BEHALF OF ISSUING BANK.
DATE RECORDED: 14/03/2022
BANK OFFICER: RUBIN CROUSE
RBC.HAMBURG@DB.COM
ID: 42345
ANSWER BACK PAGE CONFIRMATION SYSTEM
|==============|===============|============|============|========|================|
| START TIME | END TIME | DATE | USAGE TIME | MODE  | MESSAGE TYPE | PAGE | RESULT |
|--------------|---------------|------------|------------|--------|----------------|
| 12:37:49 GMT | 01:03:53 GMT  | 15/06/2022 | 3456” | I  | MT-199 | 02   | RECEIVED|
|==============|===============|============|============|========|================|
------------------------------------------------------------------------------------
SCREEN PAGE REFERENCE:* DEUTDEFFXXX-3691NV2022- BNINIDJAXXX*NORMAL
MESSAGE INPUT REFERENCE: S005493022062901
CNF,--------------------------------------------------------VALID
RFE-DTM,----------------------------------------------------VALID
RFE,--------------------------------------------------------VALID
DTM,--------------------------------------------------------VALID
NAD-CTA-COM-------------------------------------------------VALID
NAD,--------------------------------------------------------VALID
CTA,--------------------------------------------------------VALID
COM,--------------------------------------------------------VALID
ERC-FTX-5G4,------------------------------------------------VALID
ERC,--------------------------------------------------------VALID
FTX,--------------------------------------------------------VALID
REF-FTX,----------------------------------------------------VALID
BEF,--------------------------------------------------------VALID
FTX,--------------------------------------------------------VALID
UNT,--------------------------------------------------------VALID
RMA,--------------------------------------------------------VALID
----------------------------------------------------------------------------
THE DEUTSCHE BANK PRIVAT UND GESCHAFTSKUNDEN AG ACKNOWLEDGMENT AND RECEIPT
----------------------------------------------------------------------------
